import { Article, Author, Category, Product } from '@/types'

export const authors: Author[] = [
  { id: '1', name: 'David Peterson', avatar: 'https://i.pravatar.cc/150?img=1' },
  { id: '2', name: 'Anna Luis', avatar: 'https://i.pravatar.cc/150?img=5' },
  { id: '3', name: 'Sarah Eddrissi', avatar: 'https://i.pravatar.cc/150?img=9' },
  { id: '4', name: 'Nisi Nyung', avatar: 'https://i.pravatar.cc/150?img=12' },
]

export const categories: Category[] = [
  { id: '1', name: 'Politics', slug: 'politics' },
  { id: '2', name: 'Opinions', slug: 'opinions' },
  { id: '3', name: 'World', slug: 'world' },
  { id: '4', name: 'Media', slug: 'media' },
  { id: '5', name: 'Tech', slug: 'tech' },
  { id: '6', name: 'Business', slug: 'business' },
  { id: '7', name: 'Fashion', slug: 'fashion' },
  { id: '8', name: 'Arts', slug: 'arts' },
  { id: '9', name: 'Food', slug: 'food' },
  { id: '10', name: 'Economy', slug: 'economy' },
  { id: '11', name: 'Finance', slug: 'finance' },
  { id: '12', name: 'Education', slug: 'education' },
  { id: '13', name: 'Health', slug: 'health' },
]

export const articles: Article[] = [
  {
    id: '1',
    title: 'The Rise of AI-Powered Personal Assistants: How They Manage',
    excerpt: 'Law enforcement officers have been accused of sexually abusing children over the past two decades, a Post investigation found. Nisi dignissim tortor sed quam sed ipsum ut.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800',
    category: 'Tech',
    author: authors[0],
    publishedAt: new Date(Date.now() - 60000).toISOString(),
    views: 2,
    comments: 0,
    tags: ['AI', 'Technology', 'Future'],
    featured: true,
  },
  {
    id: '2',
    title: 'Tech Innovations Reshaping the Retail Landscape: AI Payments',
    excerpt: 'Officers have been accused of sexually abusing children over the past two decades, a Post investigation found. Nisi dignissim tortor sed quam sed ipsum ut.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
    category: 'Tech',
    author: authors[0],
    publishedAt: new Date(Date.now() - 3300000).toISOString(),
    views: 100,
    comments: 5,
    tags: ['AI', 'Retail', 'Payments'],
  },
  {
    id: '3',
    title: 'Balancing Work and Wellness: Tech Solutions for Healthy',
    excerpt: 'Children over the past two decades, a Post investigation found. Nisi dignissim tortor sed quam sed ipsum ut.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800',
    category: 'Health',
    author: authors[2],
    publishedAt: new Date(Date.now() - 3600000).toISOString(),
    views: 0,
    comments: 0,
    tags: ['Health', 'Wellness', 'Work'],
  },
  {
    id: '4',
    title: 'The Importance of Sleep: Tips for Better Rest and Recovery',
    excerpt: 'Post investigation found. Nisi dignissim tortor sed quam sed ipsum ut.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800',
    category: 'Health',
    author: authors[2],
    publishedAt: new Date(Date.now() - 7200000).toISOString(),
    views: 0,
    comments: 0,
    tags: ['Sleep', 'Health', 'Recovery'],
  },
  {
    id: '5',
    title: 'The Future of Sustainable Living: Driving Eco-Friendly Lifestyles',
    excerpt: 'Nisi dignissim tortor sed quam sed ipsum ut. Dolor sit amet, consectetur adipiscing elit To spread the word, the company embarked on a mass marketing drive.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800',
    category: 'Business',
    author: authors[1],
    publishedAt: new Date(Date.now() - 43200000).toISOString(),
    views: 1,
    comments: 0,
    tags: ['Sustainability', 'Eco-Friendly', 'Future'],
    featured: true,
  },
  {
    id: '6',
    title: 'Business Agility the Digital Age: Leveraging AI and Automation',
    excerpt: 'To spread the word, the company embarked on a mass marketing drive. TV campaigns launched in the platform\'s key markets.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800',
    category: 'Business',
    author: authors[3],
    publishedAt: new Date(Date.now() - 604800000).toISOString(),
    views: 23,
    comments: 3,
    tags: ['Business', 'AI', 'Automation'],
  },
  {
    id: '7',
    title: 'The Art of Baking: From Classic Bread to Artisan Pastries',
    excerpt: 'To spread the word, the company embarked on a mass marketing drive. TV campaigns launched in the platform\'s key markets.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
    category: 'Food',
    author: authors[3],
    publishedAt: new Date(Date.now() - 777600000).toISOString(),
    views: 112,
    comments: 15,
    tags: ['Food', 'Baking', 'Recipes'],
  },
  {
    id: '8',
    title: 'Hidden Gems: Underrated Travel Destinations Around the World',
    excerpt: 'To spread the word, the company embarked on a mass marketing drive. TV campaigns launched in the platform\'s key markets.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800',
    category: 'Arts',
    author: authors[0],
    publishedAt: new Date(Date.now() - 1987200000).toISOString(),
    views: 15,
    comments: 2,
    tags: ['Travel', 'Destinations', 'World'],
  },
  {
    id: '9',
    title: 'Eco-Tourism: Traveling Responsibly and Sustainably',
    excerpt: 'To spread the word, the company embarked on a mass marketing drive. TV campaigns launched in the platform\'s key markets.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    category: 'World',
    author: authors[2],
    publishedAt: new Date(Date.now() - 2505600000).toISOString(),
    views: 20,
    comments: 3,
    tags: ['Travel', 'Eco', 'Sustainability'],
  },
  {
    id: '10',
    title: 'Tech Tools for your Time Management: Enhancing Productivity',
    excerpt: 'To spread the word, the company embarked on a mass marketing drive. TV campaigns launched in the platform\'s key markets.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800',
    category: 'Tech',
    author: authors[1],
    publishedAt: new Date(Date.now() - 7776000000).toISOString(),
    views: 19,
    comments: 4,
    tags: ['Tech', 'Productivity', 'Tools'],
  },
  {
    id: '11',
    title: 'Smart Homes, Smarter Living: Exploring IoT and AI',
    excerpt: 'To spread the word, the company embarked on a mass marketing drive. TV campaigns launched in the platform\'s key markets.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    category: 'Tech',
    author: authors[0],
    publishedAt: new Date(Date.now() - 1987200000).toISOString(),
    views: 15,
    comments: 2,
    tags: ['IoT', 'AI', 'Smart Homes'],
  },
  {
    id: '12',
    title: 'How Businesses Are Adapting to E-Commerce and AI Integration',
    excerpt: 'To spread the word, the company embarked on a mass marketing drive. TV campaigns launched in the platform\'s key markets.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=800',
    category: 'Business',
    author: authors[3],
    publishedAt: new Date(Date.now() - 2505600000).toISOString(),
    views: 20,
    comments: 5,
    tags: ['Business', 'E-Commerce', 'AI'],
  },
  {
    id: '13',
    title: 'Technology: Wearables, AR, and AI in the Apparel Industry',
    excerpt: 'To spread the word, the company embarked on a mass marketing drive. TV campaigns launched in the platform\'s key markets.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
    category: 'Fashion',
    author: authors[1],
    publishedAt: new Date(Date.now() - 5184000000).toISOString(),
    views: 5,
    comments: 1,
    tags: ['Fashion', 'Wearables', 'AR'],
  },
  {
    id: '14',
    title: 'Solo Travel: Some Tips and Destinations for the Adventurous Explorer',
    excerpt: 'To spread the word, the company embarked on a mass marketing drive. TV campaigns launched in the platform\'s key markets.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800',
    category: 'Arts',
    author: authors[0],
    publishedAt: new Date(Date.now() - 5184000000).toISOString(),
    views: 5,
    comments: 1,
    tags: ['Travel', 'Solo', 'Adventure'],
  },
  {
    id: '15',
    title: 'AI and Marketing: Unlocking Customer Insights',
    excerpt: 'To spread the word, the company embarked on a mass marketing drive. TV campaigns launched in the platform\'s key markets.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
    category: 'Business',
    author: authors[2],
    publishedAt: new Date(Date.now() - 1296000000).toISOString(),
    views: 2,
    comments: 0,
    tags: ['AI', 'Marketing', 'Insights'],
  },
  {
    id: '16',
    title: 'Gaming in the Age of AI: Strategies for Startups',
    excerpt: 'To spread the word, the company embarked on a mass marketing drive. TV campaigns launched in the platform\'s key markets.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800',
    category: 'Tech',
    author: authors[3],
    publishedAt: new Date(Date.now() - 23328000000).toISOString(),
    views: 19,
    comments: 3,
    tags: ['Gaming', 'AI', 'Startups'],
  },
  {
    id: '17',
    title: 'Virtual Reality and Mental Health: Exploring the Therapeutic',
    excerpt: 'To spread the word, the company embarked on a mass marketing drive. TV campaigns launched in the platform\'s key markets.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=800',
    category: 'Health',
    author: authors[2],
    publishedAt: new Date(Date.now() - 5184000000).toISOString(),
    views: 290,
    comments: 45,
    tags: ['VR', 'Mental Health', 'Therapy'],
  },
  {
    id: '18',
    title: 'AI-Powered Financial Planning: How Algorithms Revolutionizing',
    excerpt: 'To spread the word, the company embarked on a mass marketing drive. TV campaigns launched in the platform\'s key markets.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800',
    category: 'Finance',
    author: authors[2],
    publishedAt: new Date(Date.now() - 5184000000).toISOString(),
    views: 2,
    comments: 0,
    tags: ['AI', 'Finance', 'Planning'],
  },
  {
    id: '19',
    title: 'A Guide to The Rise of Gourmet Street Food: Trends and Top Picks',
    excerpt: 'To spread the word, the company embarked on a mass marketing drive. TV campaigns launched in the platform\'s key markets.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
    category: 'Food',
    author: authors[3],
    publishedAt: new Date(Date.now() - 15552000000).toISOString(),
    views: 2,
    comments: 0,
    tags: ['Food', 'Street Food', 'Gourmet'],
  },
  {
    id: '20',
    title: 'Top Independent Contractors to Invest in Best of Startups',
    excerpt: 'To spread the word, the company embarked on a mass marketing drive. TV campaigns launched in the platform\'s key markets.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800',
    category: 'Business',
    author: authors[1],
    publishedAt: new Date(Date.now() - 31536000000).toISOString(),
    views: 12,
    comments: 2,
    tags: ['Business', 'Startups', 'Investment'],
  },
  {
    id: '21',
    title: 'Political Landscape Shifts: New Policies Reshape National Discourse',
    excerpt: 'To spread the word, the company embarked on a mass marketing drive. TV campaigns launched in the platform\'s key markets.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800',
    category: 'Politics',
    author: authors[0],
    publishedAt: new Date(Date.now() - 86400000).toISOString(),
    views: 45,
    comments: 8,
    tags: ['Politics', 'Policy', 'National'],
  },
  {
    id: '22',
    title: 'Election Reform: What Voters Need to Know',
    excerpt: 'To spread the word, the company embarked on a mass marketing drive. TV campaigns launched in the platform\'s key markets.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=800',
    category: 'Politics',
    author: authors[1],
    publishedAt: new Date(Date.now() - 172800000).toISOString(),
    views: 32,
    comments: 6,
    tags: ['Politics', 'Election', 'Reform'],
  },
  {
    id: '23',
    title: 'Opinion: The Future of Digital Democracy',
    excerpt: 'To spread the word, the company embarked on a mass marketing drive. TV campaigns launched in the platform\'s key markets.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800',
    category: 'Opinions',
    author: authors[2],
    publishedAt: new Date(Date.now() - 259200000).toISOString(),
    views: 28,
    comments: 5,
    tags: ['Opinions', 'Democracy', 'Digital'],
  },
  {
    id: '24',
    title: 'Media Evolution: How News Consumption Has Changed',
    excerpt: 'To spread the word, the company embarked on a mass marketing drive. TV campaigns launched in the platform\'s key markets.',
    content: 'Full article content here...',
    image: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800',
    category: 'Media',
    author: authors[3],
    publishedAt: new Date(Date.now() - 345600000).toISOString(),
    views: 18,
    comments: 3,
    tags: ['Media', 'News', 'Evolution'],
  },
]

export const products: Product[] = [
  {
    id: '1',
    name: 'Laptop Cover',
    description: 'Protective cover for your laptop',
    price: 24.00,
    image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=400',
    category: 'Accessories',
    inStock: true,
  },
  {
    id: '2',
    name: 'Disney Toys',
    description: 'Collection of Disney character toys',
    price: 5.00,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    category: 'Toys',
    inStock: true,
  },
  {
    id: '3',
    name: 'Screen Axe',
    description: 'Premium screen cleaning tool',
    price: 19.00,
    image: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=400',
    category: 'Accessories',
    inStock: true,
  },
  {
    id: '4',
    name: 'Airpods Pro',
    description: 'Wireless earbuds with noise cancellation',
    price: 49.00,
    image: 'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=400',
    category: 'Electronics',
    inStock: true,
  },
]

export function formatTimeAgo(date: string): string {
  const now = new Date()
  const past = new Date(date)
  const diffInSeconds = Math.floor((now.getTime() - past.getTime()) / 1000)

  if (diffInSeconds < 60) return `${diffInSeconds}min`
  if (diffInSeconds < 3600) return `${Math.floor(diffInSeconds / 60)}h`
  if (diffInSeconds < 86400) return `${Math.floor(diffInSeconds / 3600)}h`
  if (diffInSeconds < 2592000) return `${Math.floor(diffInSeconds / 86400)}d`
  if (diffInSeconds < 31536000) return `${Math.floor(diffInSeconds / 2592000)}mo`
  return `${Math.floor(diffInSeconds / 31536000)}yr`
}

